export { default as Landing } from './landing/Landing';
export { default as Dashboard } from './dashboard/Dashboard';
export { default as Profile } from './profile/Profile';
export { default as Test } from './test/Test';
export { default as Admin } from './admin/Admin';
export { default as Opening } from './opening/Opening';
export { default as Institute} from './institute/Institute';
export { default as Ml} from './ML/ml';
export { default as Notes} from './notes/Notes';
export { default as Contact} from './contact/Contact';
// export { default as QuizInstructions} from './instruction/QuizInstructions';
// export { default as Home} from './home/Home';